#!/usr/bin/env bash
pip install -U pip
#pip install pyopenssl ndg-httpsclient pyasn1

project_name=$(basename $VIRTUAL_ENV)

if [ ! -d /local/$project_name ]; then
  mkdir /local/$project_name
fi

cd /local/$project_name

# Create a .env file at the base of the new virtualenv
echo "source $WORKON_HOME/$project_name/bin/activate" > .env
