#!/usr/bin/env bash
pip install -U pip
pip install pyopenssl ndg-httpsclient pyasn1

proj_name=$(basename $VIRTUAL_ENV)

if [ ! -d /local/$proj_name ]; then
  mkdir /local/$proj_name
fi

cd /local/$proj_name

# Create a .env file at the base of the new virtualenv
echo "source $WORKON_HOME/$proj_name/bin/activate" > .env
